compatibility_date  = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
main                = "src/worker/index.ts"
name                = "trpc-tower"

[build]
command   = "pnpm build"
watch_dir = "src"

[observability]
enabled = true
