global:
    api-listen-addr: ""
    timeout: 10s
    memo: testnet token transfer
    light-cache-size: 20
    log-level: info
    ics20-memo-limit: 0
    max-receiver-size: 150
chains:
    bbn-test-5:
        type: cosmos
        value:
            key-directory: keys/bbn-test-5
            key: default
            chain-id: bbn-test-5
            rpc-addr: https://babylon-testnet-rpc.nodes.guru:443
            account-prefix: bbn
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 1ubbn
            min-gas-amount: 0
            max-gas-amount: 25000000
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    pion-1:
        type: cosmos
        value:
            key-directory: keys/pion-1
            key: default
            chain-id: pion-1
            rpc-addr: https://rpc-falcron.pion-1.ntrn.tech:443
            account-prefix: neutron
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01untrn
            min-gas-amount: 1
            max-gas-amount: 25000000
            debug: true
            timeout: 60s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    test-token-path:
        src:
            chain-id: bbn-test-5
            client-id: 07-tendermint-2
            connection-id: connection-2
        dst:
            chain-id: pion-1
            client-id: 07-tendermint-582
            connection-id: connection-522
        src-channel-filter:
            rule: ""
            channel-list: []
