name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - dev
      - main

jobs:
  set-env-vars:
    name: Set environment matrix
    runs-on: ubuntu-latest
    outputs:
      worker_envs: ${{ steps.set.outputs.worker_envs }}
    steps:
      - id: set
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo 'worker_envs=["testnet","staging"]' >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo 'worker_envs=["production"]' >> $GITHUB_OUTPUT
          else
            echo 'worker_envs=[]' >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    needs: set-env-vars
    strategy:
      matrix:
        worker: ${{ fromJson(needs.set-env-vars.outputs.worker_envs) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Wrangler
        run: npm install -g wrangler@4.11.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build App
        run: pnpm build:app
      
      - name: Deploy Worker - ${{ matrix.worker }}
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_WORKER_EDIT_API_TOKEN }}
          environment: ${{ matrix.worker }}
          workingDirectory: trpc
